spring:
  application:
    name: social-media-platform

  datasource:
    url: jdbc:mysql://localhost:3306/social_media_platform?useSSL=false
    username: root
    password: user

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true